### ISSUE TITLE
Use official images

### ISSUE THREAD

**Issue by Fale** [pires/kubernetes-nats-cluster#10]
The current image source is not up2date with the upstream. Why not moving to the upstream one?

https://hub.docker.com/_/nats/

**Comment by pires** [comment]
The only reason to have our own image is https://github.com/pires/kubernetes-nats-cluster/blob/master/Dockerfile#L12. Btw, we're moving to a different approach https://github.com/pires/nats-operator.

**Comment by Fale** [comment]
Thanks :)
