### ISSUE TITLE
Updating to gnatsd 1.0.4 causes cryptic message

### ISSUE THREAD

**Issue by verdverm** [pires/kubernetes-nats-cluster#11]
I attempted to update the binary `gnatsd` and got the following message from k8s on container crash loop:

```
kubectl logs -f po/nats-723182443-x4xb2
/gnatsd: line 1: 404:: not found
```

That's all that is displayed. Any thoughts or insights?

**Comment by verdverm** [comment]
Ah, the curl statement in the readme returned a 404, which was put into the container...

They seemed to have reorged that repo since adding arm builds

the link should be: `https://raw.githubusercontent.com/nats-io/nats-docker/master/amd64/gnatsd`

**Comment by pires** [comment]
Feel free to open a PR that adds support for version 1.0.4.
