### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by bruth** [pires/kubernetes-nats-cluster#13]
There appears to have been [two attempts](https://github.com/kubernetes/charts/pulls?q=is%3Apr+nats+is%3Aclosed), but the authors abandoned them.

**Comment by bruth** [comment]
Sorry I missed [this](https://github.com/nats-io/gnatsd/issues/582) which you are already involved with!

**Comment by pires** [comment]
Yes, the NATS team and I are resuming work on https://github.com/pires/nats-operator
