### ISSUE TITLE
When seed is self, the server no longer joins the cluster

### ISSUE THREAD

**Issue by tutman96** [pires/kubernetes-nats-cluster#2]
I have followed all the steps in the readme, however I have run into an issue. It appears as though NATS gets confused when it tries to cluster to itself. I get the error: "Detected route to self, ignoring "nats://ruser:T0pS3cr3t@nats:6222"" in the logs and the instance stops trying to contact the cluster. I think what is happening is that NATS isn't using all the addresses of the DNS and therefore randomly selecting an A record from the results. It is getting its own IP address and tries to connect to itself. Is this a problem you have also noticed, or does it eventually work itself out?

**Comment by pires** [comment]
Good question. I have seen this but only with the first node in the cluster. Is your experience any different?

**Comment by tutman96** [comment]
It appears like the first one does have the problem.... however it doesn't seem to recover. I am thinking this is an issue with nats-server. I can report an issue with them if that would be the best.

**Comment by pires** [comment]
This behavior is expected with the first node in a cluster, since Kubernetes DNS only knows about one pod, itself.

**Comment by tutman96** [comment]
The first node thought doesn't connect with the rest of the cluster correct? Or is everything connected together fine. It looked like (If A was the first instance) that B and C would discover each other, but never A. Is this correct or am I missing something?

**Comment by pires** [comment]
B would connect to A and C would connect initially either to A or B and know about the other one.

**Comment by tutman96** [comment]
So I just changed the number of replicas from 3 to 5 and one of the new instances tried to connect to itself. It basically got stuck and wouldn't connect to anyone else. I could delete that pod and then I would have a 1 in 5 chance of connecting to itself again, however this doesn't seem like a good solution.

**Comment by pires** [comment]
@tutman96 one workaround could be to run a script as `livenessProbe` and:
1) check if there is more than `0` routes established, and
2) check this is not the first node

**Comment by pires** [comment]
@tutman96 I haven't been able to replicate this.

**Comment by tutman96** [comment]
Hmm.... that is strange. I have tried a couple of more times and it will do the same. It isn't 100% reproducible because of the random DNS, but I was able to get it to happen just by starting 3 replicas. Would you mind sharing your config?

**Comment by tutman96** [comment]
I am still trying to narrow down the issue but now I get an even weirder issue. The nodes will no longer even attempt to connect to each other. There is nothing in the logs about them attempting to connect or anything. They just don't connect to each other.

**Comment by pires** [comment]
I will be working on this next week.

**Comment by pires** [comment]
Sorry, next week it is!

**Comment by pires** [comment]
I am working on this as we speak and I'm only missing the `check this is not the only running instance`.
