### ISSUE TITLE
Replace with an operator

### ISSUE THREAD

**Issue by pires** [pires/kubernetes-nats-cluster#5]
See https://coreos.com/blog/introducing-operators.html

**Comment by pires** [comment]
For the curious ones, here's the [WIP](https://github.com/pires/nats-operator).

**Comment by SEJeff** [comment]
For a new deployment, which is preferable? This, or the operator?

**Comment by pires** [comment]
So far, this. The operator works but a StatefulSet provides more guarantees as we speak.

**Comment by pires** [comment]
https://github.com/nats-io/nats-operator

**Comment by mvpmvh** [comment]
is the operator approach the canonical approach now?

**Comment by pires** [comment]
There is no canonical way. You choose what best fits yours needs.

**Comment by nightrune** [comment]
Hi @pires, What are the differences between the operator and Stateful Set with the current amount of development?
