### ISSUE TITLE
Image for 1.0.0?

### ISSUE THREAD

**Issue by bmcustodio** [pires/kubernetes-nats-cluster#9]
It would be useful to kind of "backport" 7f58995 to at least a previous version of NATS (e.g., `1.0.0`). This would enable us to better test the upgrade scenario in `pires/nats-operator` while a new version of NATS isn't released.

In order not to mess with `master` now that it targets `gnatsd-1.0.2`, I'd suggest to either...

* Create a `gnatsd-1.0.0` branch, replace the `gnatsd` binary and tag so that Quay picks it up.
* Manually create and push such an image to Quay.

I've set up what is necessary at

https://github.com/brunomcustodio/kubernetes-nats-cluster/tree/gnatsd-1.0.0

in case this sounds like a good idea. If you don't want to go through the trouble of building the image you can `docker pull quay.io/brunomcustodio/docker-nats:1.0.0`, re-tag and push to Quay.

**Comment by pires** [comment]
You have been invited to become a collaborator.

**Comment by bmcustodio** [comment]
Many thanks 🙂 This has landed on a5f24d7 (`gnatsd-1.0.0` branch) and a new image has been built, so I'm closing the issue.
